query About {
  about {
    data {
      id
      attributes {
        bio {
          id
          name
          function
          content
          image {
            ...File
          }
        }
        testimonials {
          id
          name
          function
          content
          image {
            ...File
          }
        }
        social {
          youtube
          facebook
          instagram
          linkedin
        }
        contact {
          office
          office_map
          email
          phone
        }
      }
    }
  }
}
