fragment Category on CategoryEntityResponse {
  data {
    id
    attributes {
      title
      sub_title
      description
      icon {
        ...File
      }
    }
  }
}

fragment Categories on CategoryEntityResponseCollection {
  data {
    id
    attributes {
      title
      sub_title
      description
      icon {
        ...File
      }
    }
  }
}
