fragment Course on CourseEntityResponse {
  data {
    id
    attributes {
      name
      description
      instructor
      price
      duration
      lessons
      prev_price
      overview_url
      review
      url
      slug
      createdAt
      updatedAt
      publishedAt
      cover {
        ...File
      }
      instructor_image {
        ...File
      }
      category {
        ...Category
      }
    }
  }
}

fragment Courses on CourseEntityResponseCollection {
  data {
    id
    attributes {
      name
      description
      instructor
      price
      duration
      lessons
      prev_price
      overview_url
      review
      url
      slug
      createdAt
      updatedAt
      publishedAt
      cover {
        ...File
      }
      instructor_image {
        ...File
      }
      category {
        ...Category
      }
    }
  }
  meta {
    pagination {
      total
      page
      pageSize
      pageCount
    }
  }
}
