fragment Course on CourseEntityResponse {
  data {
    id
    attributes {
      name
      description
      price
      instructor
      slug
      cover {
        ...File
      }
      instructor_image {
        ...File
      }
      category {
        ...Category
      }
      lessons {
        id
      }
    }
  }
}

fragment Courses on CourseEntityResponseCollection {
  data {
    id
    attributes {
      name
      description
      price
      instructor
      slug
      cover {
        ...File
      }
      instructor_image {
        ...File
      }
      category {
        ...Category
      }
      lessons {
        id
      }
    }
  }
  meta {
    pagination {
      total
      page
      pageSize
      pageCount
    }
  }
}
