query Courses($pagination: PaginationArg, $filters: CourseFiltersInput) {
  courses(pagination: $pagination, filters: $filters) {
    ...Courses
  }
}

query CoursesBySlug($filters: CourseFiltersInput) {
  courses(filters: $filters) {
    ...Courses
  }
}
