fragment Course on CourseEntityResponse {
  data {
    id
    attributes {
      name
      description
      price
      prev_price
      instructor
      duration
      lessons
      review
      slug
      updatedAt
      cover {
        ...File
      }
      instructor_image {
        ...File
      }
      category {
        ...Category
      }
    }
  }
}

fragment Courses on CourseEntityResponseCollection {
  data {
    id
    attributes {
      name
      description
      price
      prev_price
      instructor
      duration
      lessons
      review
      slug
      updatedAt
      cover {
        ...File
      }
      instructor_image {
        ...File
      }
      category {
        ...Category
      }
    }
  }
  meta {
    pagination {
      total
      page
      pageSize
      pageCount
    }
  }
}
