query Courses($pagination: PaginationArg, $filters: CourseFiltersInput, $sort: [String]) {
  courses(pagination: $pagination, filters: $filters, sort: $sort) {
    ...Courses
  }
}

query CoursesBySlug($filters: CourseFiltersInput) {
  courses(filters: $filters) {
    ...Courses
  }
}
